//Ensure the root element is created so the widget can be mounted
function ensureRootElement() {
  console.log("[sitescript] ensureRootElement: start");
  const existingRoot = document.getElementById("rv-site-root");
  if (existingRoot) {
    console.log("[sitescript] ensureRootElement: using existing root", existingRoot);
    return existingRoot;
  }

  const root = document.createElement("div");
  root.id = "rv-site-root";
  root.className = "rv-widget";
  console.log("[sitescript] ensureRootElement: created new root", root);
  placeRootElement(root);
  return root;
}

//Place the root element in the DOM
function placeRootElement(root) {
  console.log("[sitescript] placeRootElement: attempting placement");
  if (!document.body) {
    console.log("[sitescript] placeRootElement: document.body missing, appending to documentElement");
    document.documentElement.appendChild(root);
    return;
  }

  const header = findHeaderElement();
  if (header?.parentNode) {
    console.log("[sitescript] placeRootElement: inserting after header", header);
    header.insertAdjacentElement("afterend", root);
    return;
  }

  console.log("[sitescript] placeRootElement: header not found, appending to body");
  document.body.appendChild(root);
}

// Find the header element (<header> tag)
function findHeaderElement() {
  const header = document.querySelector("header");
  if (header) {
    console.log("[sitescript] findHeaderElement: header found", header);
    return header;
  }

  console.log("[sitescript] findHeaderElement: header not found");
  return null;
}

//Create the content for the widget
function renderHelloContent(target) {
  console.log("[sitescript] renderHelloContent: rendering into", target);

  if (!target || !(target instanceof HTMLElement)) {
    console.warn("[sitescript] renderHelloContent: invalid target");
    return;
  }

  // Load shared styles
  loadSiteScriptStyles();

  // Clear old content
  target.innerHTML = "";

  const container = document.createElement("section");
  container.className = "sitescript-fullwidth-box";

  const inner = document.createElement("div");
  inner.className = "sitescript-inner";

  const heading = document.createElement("h1");
  heading.className = "sitescript-header";
  heading.textContent = "Hello, Website!";

  const paragraph = document.createElement("p");
  paragraph.className = "sitescript-sub";
  paragraph.textContent =
    "This content was generated by calling a JavaScript function. Below are some example cards with gradient borders.";

  const rects = document.createElement("div");
  rects.className = "sitescript-rects";

  const cards = [
    { title: "Quick stats", body: "Revenue and KPIs", gradient: "linear-gradient(90deg, #6a11cb, #2575fc)" },
    { title: "Tasks", body: "Pending items", gradient: "linear-gradient(90deg, #ff7a18, #af002d, #319197)" },
    { title: "Activity", body: "Recent user activity", gradient: "linear-gradient(90deg, #00b09b, #96c93d)" },
    { title: "Notes", body: "Resources and links", gradient: "linear-gradient(90deg, #f7797d, #FBD786, #C6FFDD)" }
  ];

  cards.forEach((c) => {
    const wrap = document.createElement("div");
    wrap.className = "sitescript-rect";
    wrap.style.setProperty("--g", c.gradient);

    const innerCard = document.createElement("div");
    innerCard.className = "inner";

    const t = document.createElement("h3");
    t.className = "title";
    t.textContent = c.title;

    const b = document.createElement("p");
    b.className = "body";
    b.textContent = c.body;

    innerCard.appendChild(t);
    innerCard.appendChild(b);
    wrap.appendChild(innerCard);
    rects.appendChild(wrap);
  });

  inner.appendChild(heading);
  inner.appendChild(paragraph);
  inner.appendChild(rects);
  container.appendChild(inner);
  target.appendChild(container);

  console.log("[sitescript] renderHelloContent: render complete");
}


//Mount the widget to the page
function mountHelloWidget() {
  console.log("[sitescript] mountHelloWidget: start");
  try {
    const root = ensureRootElement();
    console.log("[sitescript] mountHelloWidget: root ready", root);
    renderHelloContent(root);
  } catch (error) {
    console.error("sitescript.js failed to mount:", error);
  }
}

//Initialize the widget
function initializeWidget() {
  console.log("[sitescript] initializeWidget: document.readyState", document.readyState);
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => {
      console.log("[sitescript] initializeWidget: DOMContentLoaded fired");
      mountHelloWidget();
    }, { once: true });
    return;
  }

  mountHelloWidget();
}

function loadSiteScriptStyles() {
  if (document.getElementById("sitescript-shared-styles")) return; // already loaded

  const css = `
    .sitescript-fullwidth-box {
      width: 100%;
      box-sizing: border-box;
      background: #f2f2f2;
      padding: 28px 16px;
      display: flex;
      justify-content: center;
    }

    .sitescript-inner {
      width: 100%;
      max-width: 1200px;
      box-sizing: border-box;
    }

    .sitescript-header {
      margin: 0 0 16px 0;
      font-size: 1.6rem;
      font-weight: 600;
      color: #111;
    }

    .sitescript-sub {
      margin: 0 0 20px 0;
      color: #333;
      opacity: 0.9;
    }

    .sitescript-rects {
      display: flex;
      gap: 16px;
      flex-wrap: wrap;
    }

    .sitescript-rect {
      border-radius: 12px;
      padding: 3px;
      background: linear-gradient(90deg, #ff7a18 0%, #af002d 40%, #319197 100%);
      box-sizing: border-box;
      flex: 0 1 calc(25% - 12px);
      min-width: 190px;
    }

    .sitescript-rect[style*="--g:"] {
      background: var(--g);
    }

    .sitescript-rect .inner {
      display: flex;
      flex-direction: column;
      gap: 8px;
      background: #fff;
      border-radius: 9px;
      padding: 14px;
      min-height: 110px;
      box-sizing: border-box;
      box-shadow: 0 1px 2px rgba(0,0,0,0.04);
    }

    .sitescript-rect .title {
      margin: 0;
      font-size: 1rem;
      font-weight: 600;
    }

    .sitescript-rect .body {
      margin: 0;
      font-size: 0.9rem;
      opacity: 0.95;
    }

    @media (max-width: 900px) {
      .sitescript-rect { flex: 0 1 calc(50% - 12px); }
    }
    @media (max-width: 520px) {
      .sitescript-inner { padding: 0 8px; }
      .sitescript-rect { flex: 0 1 100%; }
    }
  `;

  const style = document.createElement("style");
  style.id = "sitescript-shared-styles";
  style.textContent = css;
  document.head.appendChild(style);
}


initializeWidget();

if (typeof window !== "undefined") {
  console.log("[sitescript] expose mount function on window");
  window.rvMountHelloWidget = mountHelloWidget;
}