//Ensure the root element is created so the widget can be mounted
function ensureRootElement() {
  console.log("[sitescript] ensureRootElement: start");
  const existingRoot = document.getElementById("rv-site-root");
  if (existingRoot) {
    console.log("[sitescript] ensureRootElement: using existing root", existingRoot);
    return existingRoot;
  }

  const root = document.createElement("div");
  root.id = "rv-site-root";
  root.className = "rv-widget";
  console.log("[sitescript] ensureRootElement: created new root", root);
  placeRootElement(root);
  return root;
}

//Place the root element in the DOM
function placeRootElement(root) {
  console.log("[sitescript] placeRootElement: attempting placement");
  if (!document.body) {
    console.log("[sitescript] placeRootElement: document.body missing, appending to documentElement");
    document.documentElement.appendChild(root);
    return;
  }

  const header = findHeaderElement();
  if (header?.parentNode) {
    console.log("[sitescript] placeRootElement: inserting after header", header);
    header.insertAdjacentElement("afterend", root);
    return;
  }

  console.log("[sitescript] placeRootElement: header not found, appending to body");
  console.log("[sitescript] placeRootElement: no anchor found, appending to body");
  document.body.appendChild(root);
}

// Find the header element (<header> tag)
function findHeaderElement() {
  const header = document.querySelector("header");
  if (header) {
    console.log("[sitescript] findHeaderElement: header found", header);
    return header;
  }

  console.log("[sitescript] findHeaderElement: header not found");
  return null;
}

//Create the content for the widget
function renderHelloContent(target) {
  console.log("[sitescript] renderHelloContent: rendering into", target);
  target.innerHTML = "";

  const heading = document.createElement("h1");
  heading.textContent = "Hello, Website!";

  const paragraph = document.createElement("p");
  paragraph.textContent = "This content was generated by calling a JavaScript function.";

  target.appendChild(heading);
  target.appendChild(paragraph);
  console.log("[sitescript] renderHelloContent: render complete");
}

//Mount the widget to the page
function mountHelloWidget() {
  console.log("[sitescript] mountHelloWidget: start");
  try {
    const root = ensureRootElement();
    console.log("[sitescript] mountHelloWidget: root ready", root);
    renderHelloContent(root);
  } catch (error) {
    console.error("sitescript.js failed to mount:", error);
  }
}

//Initialize the widget
function initializeWidget() {
  console.log("[sitescript] initializeWidget: document.readyState", document.readyState);
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => {
      console.log("[sitescript] initializeWidget: DOMContentLoaded fired");
      mountHelloWidget();
    }, { once: true });
    return;
  }

  mountHelloWidget();
}

initializeWidget();

if (typeof window !== "undefined") {
  console.log("[sitescript] expose mount function on window");
  window.rvMountHelloWidget = mountHelloWidget;
}