function ensureRootElement() {
  const existingRoot = document.getElementById("rv-site-root");
  if (existingRoot) {
    return existingRoot;
  }

  const root = document.createElement("div");
  root.id = "rv-site-root";
  root.className = "rv-widget";
  document.body.insertBefore(root, document.body.firstElementChild);
  return root;
}

function renderHelloContent(target) {
  target.innerHTML = "";

  const heading = document.createElement("h1");
  heading.textContent = "Hello, Website!";

  const paragraph = document.createElement("p");
  paragraph.textContent = "This content was generated by calling a JavaScript function.";

  target.appendChild(heading);
  target.appendChild(paragraph);
}

function mountHelloWidget() {
  try {
    const root = ensureRootElement();
    renderHelloContent(root);
  } catch (error) {
    console.error("sitescript.js failed to mount:", error);
  }
}

function initializeWidget() {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mountHelloWidget, { once: true });
    return;
  }

  mountHelloWidget();
}

initializeWidget();

if (typeof window !== "undefined") {
  window.rvMountHelloWidget = mountHelloWidget;
}